services:
  arkham-base:
    build: .
    volumes:
      - ./source:/app/source
      - ./out:/app/out
      - ./glossary:/app/glossary
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: bash

  converter:
    extends:
      service: arkham-base
    command: python converter.py

  translator:
    extends:
      service: arkham-base
    command: python translator.py
