services:
  arkhamdb-translator:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./source:/data/source:ro
      - ./out:/app/out
      - ./glossary.json:/app/glossary.json
      - cache_volume:/app/.cache
    command:
      [
        "--root", "/data",
        "--out", "/app/out",
        "--glossary", "/app/glossary.json",
        "--cache", "/app/.cache/cache.sqlite"
      ]

volumes:
  cache_volume:
